import sys
import subprocess
import time
import tempfile
import os
from typing import Dict, Any

class SubprocessSandboxRunner:
    """
    Executes Python scripts generated by worker agents in an isolated subprocess sandbox.
    Captures stdout, stderr, execution time, and exit status codes for self-healing loops.
    """
    def __init__(self, timeout_seconds: int = 15):
        self.timeout_seconds = timeout_seconds

    def execute_code(self, code_content: str) -> Dict[str, Any]:
        start_time = time.time()
        
        # Write code to a temporary file
        with tempfile.NamedTemporaryFile(suffix=".py", mode="w", delete=False, encoding="utf-8") as temp_file:
            temp_file.write(code_content)
            temp_path = temp_file.name

        try:
            # Run in isolated subprocess
            process = subprocess.Popen(
                [sys.executable, temp_path],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
            )
            
            try:
                stdout, stderr = process.communicate(timeout=self.timeout_seconds)
                exit_code = process.returncode
            except subprocess.TimeoutExpired:
                process.kill()
                stdout, stderr = process.communicate()
                exit_code = -1
                stderr = f"Execution Timed Out after {self.timeout_seconds} seconds.\n" + (stderr or "")

            duration_ms = round((time.time() - start_time) * 1000, 2)

            return {
                "success": exit_code == 0,
                "exit_code": exit_code,
                "stdout": stdout or "",
                "stderr": stderr or "",
                "duration_ms": duration_ms
            }

        except Exception as e:
            return {
                "success": False,
                "exit_code": 1,
                "stdout": "",
                "stderr": str(e),
                "duration_ms": round((time.time() - start_time) * 1000, 2)
            }
        finally:
            if os.path.exists(temp_path):
                try:
                    os.remove(temp_path)
                except Exception:
                    pass

sandbox_runner = SubprocessSandboxRunner()
